input = <<~INPUT
nwnwesenenewnwswnwweewswwweswwsew
wswnewwwwwwwswswseswswswwwwesw
eeneeeeseswenweeswneneeneeneene
nwnwnwnwnwnwnwnwnwnwsenwnwnwnwnwnwwenwnw
swneswnwneseswenwnwnwwseneneswnenenene
nwnenwnenwnwneenwnwneneneneswnenene
seneswsesesesesesewnesesesesesewsesese
neseseesewwwnwswseseseswseneswswseee
eneneeeneeeneneeenewneneneee
seseeeneseseeseseseeeeseeewse
swneswewswwswwnwenwsewwnewwwww
wswwwwwwnwwwnwsewnew
neeeneeeeeeeweeeneneseneeenw
eneewenwnenwswnwneswnwnwswesenwnwne
eeeeeenewsweeeeseene
swnwseswseswsenenesenewsesesenwsesesesese
wswnwnwwwwwwwwwnwwseenwwnwnwnw
neeweseseeeenweewweesenwnee
swswnenwsweenwwswswswswswnwswwwswsee
nwseseewsenwswnenwnwsewneswewnwnwnwenw
nwnwnenwswnenwnwnenwnenwnenwnwnwnwswnwnwe
swneenwneneswnenenenenenenenenwnwneneswnene
senwnwneneneenewnwnwnwenwnenwnenwwnwnw
swwnwwwwwwwswneswewwwewwswe
neewneweswnwnweseswnwwneeneswnwnw
nenenweeeeneneswneswnesweenenenewe
seeswswwswswswswsweswswseswwswswswswsw
seseseseneeseseeswsesesesenwsesenwswse
ewenwsewnwwnwnwwnwwnwnwwwwww
sewnwwwnwwnwewnwwswwwwnwnwww
wswnweswswwswwesesweneseswneswwesw
sewswswneswswwswswwswswswswswwwswsw
swseswwseswswswseswseseneseseneseseswswse
seswswesewseswsesenwseseesewneseswswswsw
neeenwneneswneneneeneswenewnwenesw
wsewenewwwwwwwnwwwswenwnwswe
neseswseseswswswsenwnwswwswseswseneesee
swnenenwenesweeneeeeswnwneenenee
wwwwwnwwwswwswwwwwseww
seenwseeseseseeweseseeeeenwsese
seeswnwsesenenweneseenwswswseswsesese
swswweneweeeeswseneenwnwneeene
wnwwswwwwwswwseswswswswwwwsw
nwwnewewnwewswwswewnwwwnwwswe
eeewseeneesweeeenwwnwseeeese
wswswneswswswnwswswwwswwswswswswwesww
neweneeswnwnwenenenwnenwnwnwwnwsesw
seswesesenenwewnwneewnewnwnewneew
swwenewsenenewneneneneneneeswswewe
nwnwnwseenwwnwnwwnwnwwneswwnwwwnw
nwnwswswwwnewswneewwnwwwwwnww
wnwnwwwnwenwnwewwnwswnw
swswswswswwswswneswswswswswseswwswswnw
sesewswseseseseeseswsesenwseseseesesw
eeweneeneeeeesweeneeeenee
wnwnwnesenenwnwswswwnwnwnenenwneeseswnw
seswseswswsesesesesesesewseseseseneese
seseseeseseweseseseeseseeseese
enweneseseeseeseseseseeeeseew
eneneneeneenenenenesenwnene
nenwnenesenenwwnewnwnwenenwe
wwneseneswswsenewwwwwwseeswwnwe
seseeeseseseseswnwwseesweenenesewnee
wwneseswsewseeseseswsesesenwsesesesee
swswswswswswesewwwswswswnewswswsww
eesweeswswwswenwenwnwnwsenwnwswe
nenenewneneneneneneenewneneneneenene
wwswnenwnwnwenwswnenwswswewnewesesw
eeseeeseeseeeseseweneeseeeewse
ewwwnwnwwsenwwwwnwwwwwwwww
seseneswsesenewseseswseseswsesesesesesesese
seneseneseswwseesesesesesenewseswesenw
nwswswnewswswswwwswwwewnewsewse
swnwswseseswneweseseseseswswenenwnwsw
eeneenenewweeeeeneeseewnee
wwnwwwwnwwewnwswwwnwewwne
swwswswswwnwsweswwswwwswnwseswswsw
wwswwwwsewewswnenwwsewswswnwswsw
nwsenwnwswnwnwnwnwnwnwwnwnwnwnwwenwnw
nenwnwnwnwnwnwnwnwnwnwsenwneswwnwnwnene
nwseeswesenwseseswsewnesenww
nenwwnwnwnwsenwnenwwwnwnwnwswnwwnwnw
swwwswswwwswswswnewsw
nenenwneneneneswnwsenenwnenenenwnenwnwnw
wwwnewwswswseswwwwwwsenwwwwwsw
nwnwewwwnwswnwwnwneeenwswewswsw
swswswswseswswswswswnweswswswswswswsweswnw
nenwenewnenweswneneenwnenenenenwseneswne
seswsenwwnenwseseseswsewsenesesesenw
neenweneneeeeneeeneeesweneeesw
nwnwsenwnwnwwnwnwnwnwwnwnwnwsenenwnenwnwnw
swseswseswwswswseseseneswswseswsesesese
sesesesesesenwseseeswswseseeseneeese
wwnenewwwwwsewwnwwswwwwnwse
nweeeswnweswesenwsenweweenwswe
swseswswseswwswswswswswswswswswwneeswse
wwnwnwwnwnewnwnwnwnwsewwewnwnwse
enewwswneeneswe
sweneswswswnwwseswswwswewseswnenenesww
ewwwswwwnesewwsenweneswnwneswesw
swwwneswswswnwswwswwswwsewnenwswewne
seeseswseswseswsenwswseseswseseesewse
senewnesewnwwsewseseneseswneseseenwse
swwnwwewwwnwwwnwwwwnwnwwnwnw
wsenwswswswseseswswneseswseseswswsesese
nenenwnwnenwenwwnwnwneeswnwswnenwwesw
weeseneeeeeneneeeneeeewenenee
nenwneeseenenenenenenenenwneswnwnenewwnw
eeeeeeseeeswneeseenwesenwesew
nwnwnenenwnwnwneeswenenenwnenenwwnene
swwnwnwnwnwnwnwnwnweeneenwnwsenwwnw
nenenenwnwneswnwswsenenwnwneenenenenwnene
eeeeeeeeeeeeewe
swnwseswsesenwsenwseswnenesenwewswswse
neswneneeneneneneseneneneneneenwnewne
nwwnwsewnwwsenwwnwnwnewwnwnwwnwnwnwnw
neswsenwnenwnenewwsesesewnwseneenwnwne
nwnwnwswnewnwnenenwnenwenwnenwnewsenw
eneewneseseneseswseseeenwsww
seesenwsweseseseeseseeesesesesesenw
senwnwnwswwnwwnesewwnwnwnenwenw
eseswneswseswnwnwsweseenewnenwnwsese
senwewseenwswneeeeeeeeeneee
swnwsenwwnwnwneneswnwewwwnwnwnwnwnwwnw
swwsesenwsesenwseeeseneseeweseseee
wwwwswwswwswwnwwswsewseneswswswsw
nenwwsewswnwnwenwnwnwnwenwnwweenwnw
swseeseeseeeeeeeeeeeeeenw
eeswweeeeneenweeee
seseseeeewseenewseeseseseseneesese
wnwnwnwnwnwnwnwnenwnwnwwsenwnwnwnwnwnw
wwswwwwswwwwwwewwwwnewww
seswnwsweweswneswseswswsesewswnwsese
swwwswswseswwswswswwswswwnwwnwwswe
swnwwnwwewnwnwwnwnwnwwnwwwwnww
nenenenwnwswswewsenwnwsenwnwesenwwnwse
seswneseneseswseseseseswseswwsewsesese
neswnenenenwnewneneeneenene
swnwswnenwneenwenwswsenwnwnewnenenene
swneswswswswwwswswswswswswswswnewswswsw
enwnwewnwswwwwnwwnwwneswwesww
senenwnenwnwnwneewnwnwnwnwnwswnenwnwsw
senwnenwwnwnwneeswnwseswnwnwseenwenwnw
wswwwwseswswwwwwwwwwneew
swwswsenwswswswswswswnwswswswswnesweeswsw
nenenenwnenenwneswneseseneneswnenew
nwewnwnwneswnwswswseseeeesweewseee
neswswwwswneswwswswsweswswswswwswsw
nwnenwnenwswneeneneneneneneswnwenenwnenw
eseeneeeseweeneseesesweeeee
neneneenwnenwewsewnenwwnenenwnwew
sweeswnwnwneeswnwwswnwnwe
nenwnenenwnenwneswneenenenenwnenesenwne
eneseswswseswneneswswwwswswsesesewsese
nwnewwnwwnwnwswwwnwwwnwwenwwsww
ewswseeeseeneneneenew
esesesenewnwwseneseseseseswnwse
nenwnwnwnwnwnwsenwsenwnenwnwnwwnewwsese
ewwwwnewswwswnewwwww
ewwwnewwnwewswnwnwwswwwnwwew
nweswswswswnwswsweswswseswwnwswseswee
seenwsesenwsewnweneseswseseseseseesese
senewseswesenwsenw
swneswswseweswseswseswneswwseswsewsesw
wnwwwswnwswnewneswseswsesewweew
nwnwsenwnwnwwnwnwnwnwnwnwnenwnw
ewenwneenwnenwneseseswneswnenenenwnwsw
seseseseseenwsweseeeseseesesenewse
eseseseseseeeeenwneeeseswwesenwee
wnwesweeswenweeeeeeeeeneee
newwnwwewswweeewnenwwswnwwsw
wwwwwwnenwwswswswweewwswswsww
senwseswsweswswswseswswwswsweswwswswsw
neneneeweneneweeeeseeenenenenee
nwswnwnweneneswsesweneneneneswsenewnene
swswnewwswnwsewwwswswwwswwwwswe
nweswsewenweeswweewneeeseesese
eeeswseeeeweeeenenwe
wswwwwnwnenwwwnwnwwnwswnwwwew
swwsweeswswwswswwseswswseswseswswe
sweswnwsweseswnwsenwswseswswwne
swsesesenwswseswnwswswneseeswseseswweswse
newwwnwwswnwnesewnwnwenwnwnwnw
eneswsesesewwenewneswseeseneneseswse
neswswwwwwswwwsenwsweswswneswww
sweneeeeneeeswesweneneneeenee
senweseneseswwswswenw
wweswwsewneswnewswneswwwsw
eeseseseesesenewsesewsesesesesesese
enwenesesesweeseeeeeeseeswesenwnw
nenenwnenenenwwswneneneneneneneneneenene
seswnewnenwswnwnwnwnwwnwnwswnenenwwnwsw
nwnenenwnenenwnwsenenenwneswnwnenenwnenee
seseswsewsesesweseswwsesesweseseswse
nesenwnwnenenenenenewneneeneneneswnenenene
nwswseswswseswswswseeseswswseswswnwswswnwse
eeeseeseneewnweeseeswseesewsee
nwnwnwswnwnwnenwnwnw
eeneeneenweeneneswenenenenweesw
wswseswswswswswseweneswsenenweswww
nwnenenwnwnwnwswenwnwsenwwnwnenenenenenwnw
wnwnenenenenwnwnenwnenwnwsenenw
seesesesweseeeseseseseseesenwse
swseseseswseseswwsesesesesesesenwseeswse
nwwnwwwwwwnwnwwsewnwsenwnwwnee
nwwnwnwwnwwnwsewwnwnwnw
eeneneneseeneswneneneeeneweewee
eneewneneneneneneeseneneswneneswnww
seswnwsesesesesweseseswswseeseswswsesesew
neeseneneenenewne
sesesweewweseseeseeenenesesewew
wsewswneswwwswswswswseesweswwnesww
eswswwswnwewneseneswwswnweenwwsw
swswswwesweswnwnwswswswswsewswsewsw
ewwswwwwnwsewnwswnewswswswwsww
eneeenewneeeneseneeneeeswnenenwne
swwwwwenwwwnwwwewseeswwwne
enwenweewsweswseeeeeseeeee
wnwwwwswwwwwswnewnewwsewenesw
seeseesesesesesewse
sewnewnwsewsewnwewnenwwwwnwswnewnw
swswswswswseswswnwswnwswseseswsesw
nwnwnwwsewnwnwnwnwnewnwnwnwnwnwnwnw
nwswswseswseswseneseseneeswswseswwswsenwse
seewneseseeeweseeeeseseseeeswsenw
eneseeweeneeeeneeeweeneneee
swswswswswswwweswwswnwseswswswswswnee
nenesewnenenwnenenene
ewwnwsesewnenwsewseneweswwnwswnw
sweneneneneesenenenenewenenenenenene
neeneneneneneeewneeeswneeneneew
wnwsenwewnwnwenwnwseswnwneweswnenenw
swswseseenwswewswswsewswswnwswseeenw
nwswwswenewewwwswswwwswwwwse
eeseseeeeeswenweeseeseeenw
neswnesenwnenenenesenwneenene
seseneseseseseeseswsesesewswsesenwsesesese
eseswseeseeseewnwwseesesesesesee
nwnwnenwnwewswnwnenenenw
weeseneeseenweneeeneeneeeee
neneneneeneneneneneneneeenenew
swwswswswswswswsenwswswswswseswneswesw
nenwnwnwnenwsewnenwenwenwsenwnwwsenwne
senwwwwneseewsenewnewwwwswnwwsw
swswswwsesewwswwwneneseenewswswswsw
newseeeeeneeseeseeweseeeseww
neneseeenenenenewnesenenwnenenenenenene
seseseesesesesesesesesesewseseseswse
newswswswswswneseswswneswswseswswwwnesw
eewneseneesenwenwneswsesewesesewse
seseseseseneseseeeeeswee
ewnenenenwnwnwnwnwnenwwnenwnwnenwenene
eweweneeswneeneeneesweenenenene
seseseseseswseewesewnesenwseseesenese
neswwseeseeswsenewnenwneswnwsenwneene
sewnwewwwnwewnwewswnewnwwswww
nenenesweeneenenwnwenenenesweeneese
nwneeseesesesesesewnwseswseweesese
nwnwnwnwnwsenesesenenenenwswnwwnwnenwwnwne
swnweswsesesesenwseseseseseseseneswnwse
eseseeseseeseseseseewsesesesewenesee
eswnwnenenwneenwneswneneneswnwswnwswne
neseseseeswsewswswswneenwwsww
eeweeesenwwsenweeeeseeee
swwswsweswswswswswsewne
senwwwweneseneweesenwnenenwnwwnw
seseseseeesesenwseesweeseseesesee
eeeneseeweeneneeeene
nwswwwenwnwnwnenwnwswswnenwnwnenenwnwsesw
nenenenwnwnwnwnenenenenwsenenwwnenenene
swswsweswswewswswswswswswswnwswnwswsw
ewswswswwwswwswnewseswwneneswwsww
swswswswnwswswswswseswsw
eswswswswwwnwswwe
esesweeseseeenesenwseeseseeseseese
swswnewswswwswswwswswswswswwseswsw
wnwnwwwnwewwwwnwwsenwnwww
seeweesesesesesenwenwswseeeeswe
swesenwnwnwnwwnwnwneenwnwswnwnwnenwnwnw
nwnwnwwwnwnwnwnwnwnwenwwsenwnenwnwnw
nenenenenenesenewneneneneneneneswenene
neswswswswnwseswswsewwwswwswsweneesw
nweseseseeseesweseneeseeseseeswsee
swswwwwwswwswwneswseewwwwwww
seeseseseseseeseesesesewsesesese
enwneswnwnenenenenwsenwswnenenenwnwse
swseswnwwswswswswswswsweswswswswsesesw
wnwwnenewneneseswswnesenwswwesewnesew
neseseseseswseseswswseseseseseswse
wwswewwneswswwwwswnwwseswwswwse
seseseseswwneseneneswswnewewenwwne
sweweseseswsenwneswwseseswsesesese
eeeeneeneeeeseeeeeswseweese
nwenwenwnwswnwswnwnwnenwnwnwnwne
nenenenewneeneesenwewneweeswseesee
nwnewewwwwwseswswwsewweneswnww
sewwnwnwneswwwnwwwnwnwwwsewwww
eeeeneeswneeeeenwnwewseswee
eswnwwwwswnesweswnesewswnwwwswswsw
nenwnwneswnenwnewnenesenwnenesenwenese
seseseseseseswnwsesesesesesenwe
nweswnwswseesenenenwswseesenww
eeeeswneweneeeeeenwnwseeesese
wswnwneswswseenenwswneswwswwnee
seenwnewneewwsenenenewnwnwseneswswse
nwswwswnwswneneswsweseswse
newnenenwnwneswnewnenesesenenwsenwnwnwne
swswwswwnwswswswneswswswewwswswswsw
swwswswneswwswnewwswwswswswsewww
wwwwenewnwsenweseewwseewww
wwwwseewwwwwwwwwwneww
seswseneseseseswnesesesesesenwswswsesese
swswneswswseenwnwseswswnwsesewswnesese
nwnenenenwneneneseneneenewnenenenenenw
eeeewesweneneneeweeswnweswnenw
seeseesesesewsenesese
nwnwseenweenenenenesweeswneneswnenenene
wswwwwswwnwwwswnwwwsewwwwwse
eseswewnwnwesesewswsweneseswnwesw
swswnwswswswseseswswswswswewswswswnwsw
ewsenenwneswseneswneswnenw
swnwnwnwnwnwnwnwnenwnwnwnweewswnwwwnw
eeeenwsenewwswswwnwwwnwwwnew
seseesewseseseseseneswweseseseseese
neswswwewswwswnew
nenenwneneenwseneneneneseeswneenewne
seenweseswseeseeese
wwwnwwwnenwesesenwnwnwnww
nwsweeswnwneseseneenwswseneswwseseneswse
sesewswsenwseseseseseswsenese
enenenenwneenesweneneeeneneeeene
nwnwneeswneneswnwnwnenenenenwenwnwnwne
swneesesesewswwnwseseneseswnwnwnesew
swsesesesenesenesesesesew
seneewnesweneneeneneneeneneenenene
ewwswseswwswsenwswwwwwswnwnwswsesw
eeeswseeneeeeeswseneseesewnewnw
seseswsewswnwseseseeswseesesewsesese
nenwswseeswnwnweenwnwneswneeswswsewnwse
seseesesweneseesese
eswnwewsweseeseeweseeesenenwse
eesenweenwswweswnweeeeseswenwse
nwneneneneneneneneneswnenene
nwnwwnenewwnwnwnwswnwwwswnwwnwwnw
seeneeewseeewsenwseesweeeseee
sewnesewweneeeenwwnewwswswwswnw
neswswwnwnwnenwnwnwwsenwnwnwnesenwnwnenw
swnwswswnenwseswneeswnweesenwnw
neswswnewnenwseeneewenene
nenwneneseswneneneneneneenenenwswnenwsene
seswwswwwneseseswswswnwnewwsesenwnesw
eeeseenwseeneseenwseeeeseweee
nwnenenesenenewnwnenwnwswenwsenenenew
nwneneeseneswsenenewnwnwnewne
wwwswswswwwsewswswwneswwneswnewse
wnwnewsenenwnwenwnw
nwwseswsenwwseswswwswwnweenwwwnwsw
nenwseneswnenwswnwenwnenwnenwnwnwwnwswe
nenweneeseenweenenwsweneseneenene
sweswswwnwswswwwwwswswswswsweww
wwneseswesewsenwwnwnenwnw
wswswswewwswwwwwsewwwswnwwww
swswneeswswswswseswseswnwewnwsenwswsesese
swwnwswsweeswneswsweseswswsenwswnwsw
wneswneseswseseswswseeseseswwseseswsese
seswnwnwswswswswsenweseswswwnwswswese
swneseseeseeseseseseseseesewneseseseese
swswswswseswswswswswswswseseneseswneswse
sewwswwswweneswswswwswswswwwswwwsw
swswswswswswswswswswswnwswswswswswswnese
wwwswwwwwwswwsenwwwwwwnesww
seseseeseswwseeneseswsesesesesenwsesesese
enwnwnenwwnwnenwnwnwnwnenwnwnenwwnee
swswsewneneswsenwseeswseseneeswsenwsenesw
sweswswswswswswsenwswswswswswswswsww
seseseseseswsenesesesewseseswswnwseseswse
seneenwweenwsesewwneeswnenwwenee
enwenewseeneeewnweseswnesenenene
wwseswswswneswswswswswwswwswsw
swseseswwneswwnenwew
eseweswswnesenweneneesee
nwnwnwnesenwnwnwnwnwnwswnwenwnwnenwnwne
swwwwwseswwwswneswswwwwswwww
nenwnwswnesweseeswnenenwneenene
neenwwewneeseneswsenwswswewnese
nwnwwnwwwenwnwnwnwnwnwswenwnwwnwnwnwnw
wwnwwwwwwwwwwwwewwww
newweeneseseenwneseswnwneeesenwnw
esweeenewneswnenenenwenee
swswwswwneswswswswwwwswwswswsw
nenenenenenenenenesenenenenewneneneswne
seseseswsesesewsesesesesenesese
ewnwseswwswswwneswswswwneswwwswnw
newnesenenenenenenenenenwweneswnenene
swneseneseseneswwsenesesesewseswswswnw
nwnwnwwnwnwwwnwnwnwnwsewnw
ewneseeeseeneeeneeewneeeeeswne
nwwnwswenwswwwnwwnenwnwnwnwwnww
sewweswwwswwenwwwwwwnwwswesw
swnwneswwsweenwwwwnwnwwnwwnwnww
neswnenwwneneswwnenwnwenwsenenesenenwnwnw
nwnwsenwswnwwwenwnwnewswswnene
seneseswseswswswswseseswseswseseseswwswne
nenwnenwnenwnwnenenwnenenwsenenenwswnwswnw
enwnweneneneneneeswneneneesweenene
swswswswswnwswswswseseswswswswneswswswsw
eeeneneenweeeeeneneeeswnwesw
eneeswsweeneeesee
seseeeseseseeeswseseseseenwnwesese
eneneneneenenenenewswneneneneeeene
enwswneenenweseswneeewswesese
wseeeswsweswnewnesesesesenwewnwnw
seseswseswseswswnesesenwseseswswswseswsenw
nenwneneneneneneewnenwnene
nwnwwenenwnenwnwseneswnwnwnwenenwnwnenw
sesewnweseswseseseseseseseseseseseseseenw
neeneeswneenwnenenenenenwneneneneswnenene
neneswneswneeswneneneneneswenenenenwnene
senewnwenweewsesesewneseswneeeswnw
nwneeewsewseneneenwnwneswenewnenwnw
sweeenwwneswnewnweeeewnenwnwswswne
esweeneweneeeeeewenwsweesw
neswnenwwwwewsenweswwnwseeewnwe
newwwwwwwwwwwwwwseeswsww
nweeseeeeesenweeeeeesweee
wnwwenwwwnwnwnwwnesww
wewswwseneswwwswnwwnwwwwwnesww
nenenenenwsweeneneeeweseswnwneene
eeeeeewsweeesenweeesenweee
eeeeeneneneneswnenewneneeeneeese
nwswswnenesenenenenesenwnenenenenenw
neeeeseseeeseeswneseeeseseeew
seswseswnwseswseseswsesesesw
swwwswwwwnwwseswwnewewwwwswsww
ewwwewsewnwwwwwwwwwwwnww
swsesesesewsesesenwseseneseseewswsese
nenenenewneneeneneswneeneneneeenenee
nwnwwwswnwwnwwenwwnwnw
senenenweswnweweneneswesenwneneneneene
enenewneneneeeneeneeseenewnenenene
sesenwnwseseeseeseeeee
seewnwswswseswswseeswswswswseswsewesw
swswswswnwwswseswswwwewwwswwwnwww
nwnwnwnwnwnwnwnwnwnwnwwnwnenwnwnenwsenw
eeeeeeeeeneweeesweeeee
eswswwwwswwswswwswswnwwwwswwsw
neneneneneenwneneneenewsewweenese
nenenwnenwneneneneneswnenwswnwnwnwnwenwnwe
nwnwsenwnwwwenwnwenwwnwsewnwnwnenw
nwsenenwnwnwnwnwnwnenwnenene
eeseneseseswnweeenwneswnwsenweseswse
enwnenesenenewnenwwwnwnenenenwnwene
nwenwnweswnwwnwnenenenenwsewnwnwnwnene
seneseseneweeweseseeenesesweee
nenenesenenwwnwnwnwnwnwsenwnwnwnwnwnwnwnwne
swswswewenwneswswnweseswnwweswswnw
nenwsenenenwnwnewnwswnenenwnenenenenenesw
nweswseenewewnwewwnwsewswnwswnww
ewseneeneeneneeneneewseneneewnenw
wwnwnwnwnwwwwnwenenwnwseswwnwwww
senenenenwnenenwnwnesenenwwswnwnwnenwnwe
eseseesweseeeeseeesweeesenenwe
neneswnenwenwsenenwsweeneneneeswsenwe
neswswsweswswswnwswswneswswswwswseswnesw
swseseseeswseswnwseseseswseseswnwsesesw
seswswseseseseswneseseswswseseseswseswnesw
ewwwwnwwwwwwwwwwwwswww
seneswwwseseseseseswsenwseneseseswseswse
wsenwsenwwnweneswseewnwnewneseseswsenw
seswswneswswneseswswseswseswseswseswsesw
weseeeenweneeeneeeneeesweeee
neneneneneswneneneenwenene
eewseesesweeeenwweeneswewene
swswswswswwswswwswsweswswnwswswswswswse
wnenwneswnwnewswnwnwsenwewnwneenenwse
neneeneneneneneewnenenesenene
eeeseenwsesweeeeweeeseeenee
wswswseswneswsweneswswneswswseswswsww
nwnwwwnwsewnwwwwnewwwnwwwww
nwnwwnwnenenenwnenesenwnenenwnenenwnwne
wswswswweswnwswswswwswswswwswswwsw
newneneneneseneneneew
eeswsweseseneenenenewseswseenwese
seenwseeswwnwwseenenenwnewnewnew
neeneeneenesesweneeneweenenweeee
swsewwnwswwswswwsenwnewswwwneswe
nenenewneneeneeeneneneneeneneneneswne
seeesewseeeeeneeesenweeeswse
sesenwseswnwswsweseswnwswnweswseswnwswsw
ewwwwwwsewwwwnwwwwwwnewwnw
nwswseswnwwwsesenwenwnewnwnwwneswnwe
swnwswswswswswswswswswswswswsweswswswsw
sesesewnwseswnwseseswseswswswesweswsw
eeseeeenwswsweeeeeeneeeeeee
nenenenenenenewseneeeeseneneenewnenene
eeeeneneeneswneneeewneneseeene
nenesenenenenenewnwnenenenenenenenenene
nwswwnwweswsweswswneneswswswsw
sewnenenenenweenew
weeswenwswsenwsenwnwnweeeswesee
esenwsenenwsesenwneswwseseswsesesesewse
nwwnwnwnwnwnwswenwneswesesenenwnwenwwsw
wwnwnwnwnwnwwwnwnwswnewwwnwwnw
nwswenweswnwnwenwenwsenwnwwnwwnenwnw
eneneweeeneesenenenwenenewneeswne
seeseeesesenesesesesewsenweswseswne
eeneneeswwneneeeneenenenenewnenene
sesenewwwwewwwwwnewswwwnwnwne
senweeswnwseseneswnwsewswesene
sesesewwsenwseneesweseeeneswsesee
wnwnwnwwwwnwwwewswnw
swwwwwewwwwwwswesw
wwnwsewsewwesenwswsenwnewwnwsenww
nwnwenwnwnenwswnenwnwnwnwnwwnwnwsenwnwse
swsewswswseseswswwwswneneewswwswne
eeeeeenweeeswweeeeenwesee
wwnenwwwnewwswwwnwsewswwwsew
nwnwnesewsenwnwenwnwnwnwnwnww
nweswnesenenenesenenewsenewneneneswne
enwseseneenwwwnwnwnewnwsw
wwwenwwswwnwwnwnwnwnwnwnwwsenwwnw
swneswswswswswwswswswswswseswswnewswsw
seseenwneseweeesweneenwseswseee
senwswnwneswwwnwseewwnewnwnwnwee
swswswswnwwwseswneneswswwwswsweswsw
nwnewsenwsewnwnwsenwwwnwnwwwwnw
nwwnwswwswswwwwwnwseeswwseswswww
seweesesenwseseenesesweneewswwse
seweenewswnwwwwwwsenenewewwsew
nwnenenenewnenwneneneneneneneswneenwnene
eeeeeeneswneseeeeeseseeeeeew
seseesesesewseseeseseseewse
nweseneseeeseseseeseseesesweeswsenwsw
seneneswnesenenenenenenenwwnwnwswnenene
swnwseseseneseswswswsweswswswswsesesewsw
wseseeneseseeneewenewneenwnenenene
enwnenesenenewseswnwnwnenenenwnewnene
eneeeeneeewee
swwswwwewesewwnesewswswnw
swwseswseeswnewsewnwnwnwwneeswesw
weeswseeneeenwsewenenwweeewe
nwswnwnenwwnwnenewwewwwwseswwenww
seeseenwnwwewwneswwnewswwwsewsw
wswswswwswswswswswseswswswwwwnwesw
newseneeneswnenwwweneneswseeeeene
seswswseswseeswwswswnwswswswsweswnw
seseseseseseseseseneseseswseseseseneswsese
nenenwnwswneeneneenenwnwnwsew
nwswwnesewswsenwswweenesesew
wswswwenwswwwsenewswswneweseswsw
seswseswswswswswnwseseneseseswsw
wswswswswswswsenweswswswswswneseswsew
eneeenenweneneneneneneswneeeene
nwwwwwwwnewwwwwwwsewwwwswe
eseseseseseseneseseswwnweseseseseese
eweseeenweeeeseseweeese
nwnenwwnwwnwnwswnwsenwnwsenwenwnewsw
nwnenwnenwnenwswnenwswnenwnwnwnenwnenenwe
eeeeeeeeneweeneeeeeeswe
esenwnewnwnwnwwsenwnwnewnewwswswne
eenwseseeeeweseeeeeeeesesese
seseswswseswswswswseseeneseswswnwswsewswsw
nwnwnwneneneneneswenenenenenenwnenene
nwnwwnwnwnwwnwwsenwenwenwnwnwnwneswsw
sewwnwwnesesesewnewewswewnwwe
sweswswwnewswswweewswnwwseswsewnwsw
wsweeeneewenwneswene
eewseseeeesesenweeseseseseseeene
wwsweeswwwnwwwwswwewswwenw
eneeneneeenweeeeeseneeeee
neseneneswwneneeneeswnewneneseenene
eeeeeseseseseeewseswsenwwseeeese
wwswwswnewswwswwswwneswwswwwsw
wswwwswewswwswswwnwwwwswe
eseeweeeeeneeeeneeneeweeee
swswswswswseswnwsweswswswswswswswswswne
sesesenwwseesenwseseseesesesesesesesese
seenwnwwneeenwswwsesweeeenwse
nwwwwwwneseewwwww
eeeeeseenwsesw
nwnenwnwnenwnwnenwnwsenenwnenewnwnwnenw
seseseseseneseeeenwseseeseseeseseew
swswnwsweseneswwswswswwswswnewswwwsw
neneeesewneneeseneeneweeeeswnew
swswswsesesweswweswswswswsweswswwnwsw
nwswseseseswseswenwseswsesw
nwneneswnwnenenesenwnwneswne
sweseseeseseesewseswsesenwseswnwsesw
swnewsenenweneneneneneesewwnwnenenwnwse
nwnwsenwnwwnwnwnwnwwnenwwnweenwnwsw
nwwnwewnwnwnwwwwnwnwwnwnwnwswwnw
swswswewswseswseseswswswswsesewswsenesesw
eeweeeeeeeeseeeeeee
neenwswsenenewneew
seswneseenwswnwseswswswswswe
nwnenwnwsesenwnwwnwnwnenwnwnenenwsenwnw
sesenwsweseeswnwseswsewwseesesesesesw
INPUT

lines = input.split("\n")

# false = white
tiles = Hash.new { false }

require 'pry'

lines.each do |line|
  parts = line.scan /[ns][ew]|w|e/
  x = 0
  y = 0
  parts.each do |d|
    if d == "ne"
      x += 0.5
      y += 1
    end
    if d == "se"
      x += 0.5
      y -= 1
    end
    if d == "nw"
      x -= 0.5
      y += 1
    end
    if d == "sw"
      x -= 0.5
      y -= 1
    end
    x += 1 if d == 'e'
    x -= 1 if d == 'w'
  end
  tiles[[x,y]] = !tiles[[x,y]]
end

puts "Part 1"
puts tiles.values.count {|v| v}

def adj(coords)
  x = coords[0]
  y = coords[1]
  results = []
  results << [x+1,y] # e
  results << [x-1,y] # w
  results << [x+0.5,y+1] # ne
  results << [x+0.5,y-1] # se
  results << [x-0.5,y+1] # nw
  results << [x-0.5,y-1] # sw
  results
end

tiles.to_a.each do |coord, value|
  adj(coord).each do |n|
    tiles[n] = false unless tiles.key?(n)
  end
end

100.times do |i|
  new_tiles = tiles.dup
  tiles.to_a.each do |coord, value|
    num_black_neighbors = adj(coord).count{|c| tiles[c]}

    if value
      # is black
      if num_black_neighbors == 0 || num_black_neighbors > 2
        #puts "Any black tile with zero or more than 2 black tiles immediately adjacent to it is flipped to white."
        new_tiles[coord] = false # flip to white
      end
    else
      # is white
      if num_black_neighbors == 2 # flip to black
        #puts "Any white tile with exactly 2 black tiles immediately adjacent to it is flipped to black."
        new_tiles[coord] = true 
      end
    end
    adj(coord).each do |n|
      new_tiles[n] = false unless new_tiles.key?(n)
    end
  end
  new_tiles.to_a.each do |coord, value|
    new_tiles.delete(coord) if !value && adj(coord).all? {|c| !new_tiles[c]}
  end
  tiles = new_tiles
  num_black = tiles.values.count {|v| v}
  puts "Day #{i+1}: #{num_black}"
end